import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import {Assistant} from "next/font/google"
import { ToastContainer } from 'react-toastify';
import GlobalProvider from "../components/Application/GlobalProvider"
const assistantFont = Assistant({
  weight: ["400","500","600","700","800"],
  subsets: ["latin"],
  display: "swap"
})

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.variable)}
    >
      <body className={` ${assistantFont.className} min-h-full flex flex-col`}>
        <GlobalProvider>
        <ToastContainer/>
        {children}
        </GlobalProvider>
        </body>
    </html>
  );
}
